### ISSUE TITLE
Share model weight

### ISSUE THREAD

**Issue by vuthehuy1997** [NTT123/aligned-vits#6]
Can you share your model weight?
- Model duration
- Model for male voice and model for female voice

Thank you

**Comment by NTT123** [comment]
@vuthehuy1997 check out these links : 
- https://huggingface.co/spaces/ntt123/Vietnam-male-voice-TTS/tree/main
- https://huggingface.co/spaces/ntt123/Vietnam-female-voice-TTS/tree/main
